export const clerkAppearance = {
  variables: {
    colorPrimary: "#7c3aed",
    colorBackground: "#0a0a0f",
    colorInputBackground: "rgba(255,255,255,0.05)",
    colorInputText: "#ededed",
    colorText: "#ededed",
    colorTextSecondary: "#9ca3af",
    colorDanger: "#ef4444",
    borderRadius: "0.75rem",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  elements: {
    card: "bg-white/5 border border-white/10 shadow-xl",
    headerTitle: "text-white",
    headerSubtitle: "text-gray-400",
    socialButtonsBlockButton: "border border-white/10 bg-white/5 hover:bg-white/10 text-white",
    socialButtonsBlockButtonText: "text-white",
    dividerLine: "bg-white/10",
    dividerText: "text-gray-500",
    formFieldLabel: "text-gray-300",
    formFieldInput: "bg-white/5 border border-white/10 text-white placeholder-gray-600 focus:border-violet-500/50",
    formButtonPrimary: "bg-violet-600 hover:bg-violet-700 active:scale-95 transition-all shadow-lg shadow-violet-500/25",
    footerActionText: "text-gray-400",
    footerActionLink: "text-violet-400 hover:text-violet-300",
    identityPreviewText: "text-white",
    identityPreviewEditButton: "text-violet-400",
  },
} as const
